# Generated by Django 4.1 on 2022-08-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.UUIDField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institute_email', models.EmailField(default='abcd@gmail.com', max_length=254)),
                ('admin_id', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('course', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.UUIDField(null=True)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.admin')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute'),
        ),
    ]
