# Generated by Django 4.1 on 2022-08-19 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=1)),
                ('sem', models.IntegerField(default=1)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.admin')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.admin')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.admin')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.course')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institute')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.teacher')),
            ],
        ),
    ]
